In [1]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import joblib

In [30]:
class perceptron:
    def __init__(self, eta, epochs):
        self.weights = np.random.randn(3) * 1e-4
        print(f"self.weights: {self.weights}")
        self.eta = eta 
        self.epochs = epochs
        
    def activationFunction(self, inputs, weights):
        z = np.dot(inputs, weights)
        return np.where(z > 0 , 1 , 0)
    
    def fit(self, X, Y):
        self.X = X
        self.y = Y
        
        X_with_bias = np.c_[self.X, -np.ones((len(self.X), 1))]
        print(f"X_with_bias: \n{X_with_bias}")
        
        
        for epoch in range(self.epochs):
            print(f"for epoch: {epoch}")
            y_hat = self.activationFunction(X_with_bias, self.weights)
            print(f"predicted value: \n{y_hat}")
            error = self.y - y_hat
            print(f"error : \n {error}")
            self.weights = self.weights + self.eta * np.dot(X_with_bias.T,error)
            print(f"updated weights: \n{self.weights}")
            
    def predict(self,X):
        X_with_bias = np.c_[X, -np.ones((len(self.X), 1))]
        return self.activationFunction(X_with_bias, self.weights)

In [31]:
# AND Operations
data = {"x1": [0,0,1,1], "x2":[0,1,0,1], "y": [0,0,0,1]}

AND = pd.DataFrame(data)
AND

x1  x2  y
0   0   0  0
1   0   1  0
2   1   0  0
3   1   1  1

In [32]:
X = AND.drop("y",axis = 1)
X

x1  x2
0   0   0
1   0   1
2   1   0
3   1   1

In [33]:
y = AND['y']
y.to_frame()

y
0  0
1  0
2  0
3  1

In [34]:
model = perceptron(eta = 0.5, epochs=10)
model.fit(X,y)

self.weights: [ 2.02772288e-05 -6.22307150e-05  1.22536890e-04]
X_with_bias: 
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
for epoch: 0
predicted value: 
[0 0 0 0]
error : 
 0    0
1    0
2    0
3    1
Name: y, dtype: int64
updated weights: 
[ 0.50002028  0.49993777 -0.49987746]
for epoch: 1
predicted value: 
[1 1 1 1]
error : 
 0   -1
1   -1
2   -1
3    0
Name: y, dtype: int64
updated weights: 
[ 2.02772288e-05 -6.22307150e-05  1.00012254e+00]
for epoch: 2
predicted value: 
[0 0 0 0]
error : 
 0    0
1    0
2    0
3    1
Name: y, dtype: int64
updated weights: 
[0.50002028 0.49993777 0.50012254]
for epoch: 3
predicted value: 
[0 0 0 1]
error : 
 0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights: 
[0.50002028 0.49993777 0.50012254]
for epoch: 4
predicted value: 
[0 0 0 1]
error : 
 0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights: 
[0.50002028 0.49993777 0.50012254]
for epoch: 5
predicted value: 
[0 0 0 1]
error : 
 0    0
1    0
2    0
3

In [35]:
model.predict(X)

array([0, 0, 0, 1])

In [37]:
# Or gate 

data = {"x1": [0,0,1,1], "x2":[0,1,0,1], "y": [0,1,1,1]}

OR = pd.DataFrame(data)
OR

x1  x2  y
0   0   0  0
1   0   1  1
2   1   0  1
3   1   1  1

In [39]:
X = OR.drop('y',axis = 1)

In [43]:
y = OR['y']
y.to_frame()


y
0  0
1  1
2  1
3  1

In [44]:
model = perceptron(eta = 0.5, epochs=10)
model.fit(X,y)

self.weights: [ 7.22287696e-05 -1.13058733e-04  4.12079851e-05]
X_with_bias: 
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
for epoch: 0
predicted value: 
[0 0 1 0]
error : 
 0    0
1    1
2    0
3    1
Name: y, dtype: int64
updated weights: 
[ 0.50007223  0.99988694 -0.99995879]
for epoch: 1
predicted value: 
[1 1 1 1]
error : 
 0   -1
1    0
2    0
3    0
Name: y, dtype: int64
updated weights: 
[ 0.50007223  0.99988694 -0.49995879]
for epoch: 2
predicted value: 
[1 1 1 1]
error : 
 0   -1
1    0
2    0
3    0
Name: y, dtype: int64
updated weights: 
[5.00072229e-01 9.99886941e-01 4.12079851e-05]
for epoch: 3
predicted value: 
[0 1 1 1]
error : 
 0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights: 
[5.00072229e-01 9.99886941e-01 4.12079851e-05]
for epoch: 4
predicted value: 
[0 1 1 1]
error : 
 0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights: 
[5.00072229e-01 9.99886941e-01 4.12079851e-05]
for epoch: 5
predicted value: 
[0 1 1 1]
error : 

In [45]:
model.predict(X)

array([0, 1, 1, 1])

In [46]:
# XOR Operation

data = {"x1": [0,0,1,1], "x2":[0,1,0,1], "y": [0,1,1,0]}

XOR = pd.DataFrame(data)
XOR

x1  x2  y
0   0   0  0
1   0   1  1
2   1   0  1
3   1   1  0

In [48]:
X = XOR.drop("y",axis =1 )
y=XOR['y']

In [49]:
model = perceptron(eta = 0.5, epochs=100)
model.fit(X,y)

self.weights: [1.10495551e-04 9.17349258e-06 6.63992188e-05]
X_with_bias: 
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
for epoch: 0
predicted value: 
[0 0 1 1]
error : 
 0    0
1    1
2    0
3   -1
Name: y, dtype: int64
updated weights: 
[-4.99889504e-01  9.17349258e-06  6.63992188e-05]
for epoch: 1
predicted value: 
[0 0 0 0]
error : 
 0    0
1    1
2    1
3    0
Name: y, dtype: int64
updated weights: 
[ 1.10495551e-04  5.00009173e-01 -9.99933601e-01]
for epoch: 2
predicted value: 
[1 1 1 1]
error : 
 0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
updated weights: 
[-4.99889504e-01  9.17349258e-06  6.63992188e-05]
for epoch: 3
predicted value: 
[0 0 0 0]
error : 
 0    0
1    1
2    1
3    0
Name: y, dtype: int64
updated weights: 
[ 1.10495551e-04  5.00009173e-01 -9.99933601e-01]
for epoch: 4
predicted value: 
[1 1 1 1]
error : 
 0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
updated weights: 
[-4.99889504e-01  9.17349258e-06  6.63992188e-05]
for epoch: 5
predic

In [50]:
model.predict(X)

array([1, 1, 1, 1])